"""criação das tabelas iniciais

Revision ID: 53c52a799b65
Revises: c13debed1168
Create Date: 2025-07-10 09:21:32.772307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53c52a799b65'
down_revision: Union[str, Sequence[str], None] = 'c13debed1168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_migrations_pkey'))
    )
    op.create_table('inventario_pontoatendimentoinfo',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('limite', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('inventario_pontoaten_group_id_1d69d9ce_fk_auth_grou'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventario_pontoatendimentoinfo_pkey')),
    sa.UniqueConstraint('group_id', name=op.f('inventario_pontoatendimentoinfo_group_id_key'))
    )
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('locations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='locations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('order_sumary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('volume_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('volume_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('volume_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('simcard_priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maquinetas_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matnr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('logistic_provider_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sales_channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_quarter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_state_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ultima_tracking', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['end_customer_id'], ['end_customers.id'], name=op.f('order_sumary_end_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_sumary_pkey'))
    )
    op.create_index(op.f('ix_order_sumary_id'), 'order_sumary', ['id'], unique=False)
    op.create_table('logistica_romaneio',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('codigo_rastreio', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='logistica_romaneio_pkey'),
    sa.UniqueConstraint('numero', name='logistica_romaneio_numero_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('logistica_romaneio_numero_d728291e_like'), 'logistica_romaneio', ['numero'], unique=False)
    op.create_table('external_order_numbers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('external_order_numbers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('erp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marketplace', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plataforma', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sales', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='external_order_numbers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_external_order_numbers_id'), 'external_order_numbers', ['id'], unique=False)
    op.create_table('carriers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('carriers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name='carriers_driver_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='carriers_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='carriers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_carriers_id'), 'carriers', ['id'], unique=False)
    op.create_table('webhook_contents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('webhook_contents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_method_external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('warehouse_address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('origin_federal_tax_payer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sales_channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date_lp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date_lp_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scheduled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('origin_quarter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_state_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_additional', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_method_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('markers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('modified', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('modified_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sales_order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipped_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shipped_date_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logistic_provider_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('origin_customer_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_customer_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_shipping_costs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_days_lp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tracking_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('external_order_numbers_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aditional_information_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carrier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aditional_information_id'], ['aditional_information.id'], name='webhook_contents_aditional_information_id_fkey'),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name='webhook_contents_carrier_id_fkey'),
    sa.ForeignKeyConstraint(['end_customer_id'], ['end_customers.id'], name='webhook_contents_end_customer_id_fkey'),
    sa.ForeignKeyConstraint(['external_order_numbers_id'], ['external_order_numbers.id'], name='webhook_contents_external_order_numbers_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='webhook_contents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_webhook_contents_id'), 'webhook_contents', ['id'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name=op.f('django_admin_log_action_flag_check')),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_auth_user_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('django_admin_log_pkey'))
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('auth_user_username_6821ab7c_like'), 'auth_user', ['username'], unique=False)
    op.create_table('end_customers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('end_customers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cellphone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_company', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('federal_tax_payer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_tax_payer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_additional', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_quarter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_state_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notify', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='end_customers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_end_customers_id'), 'end_customers', ['id'], unique=False)
    op.create_table('inventario_caixa',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('identificador', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('lote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nr_caixa', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['inventario_lotebipagem.id'], name='inventario_caixa_lote_id_715740f5_fk', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='inventario_caixa_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('inventario_caixa_lote_id_715740f5'), 'inventario_caixa', ['lote_id'], unique=False)
    op.create_table('shipment_order_volumes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shipment_order_volumes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('shipment_order_volume_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_type_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('products_nature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('products_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_icms_exempt', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('logistic_provider_tracking_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_invoice', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('modified_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logistic_provider_label_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('packaging_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('has_clarify_delivery_fail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delivered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delivered_late', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delivered_late_lp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date_lp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_date_lp_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('original_estimated_delivery_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('original_estimated_delivery_date_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('original_estimated_delivery_date_lp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('original_estimated_delivery_date_lp_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery_days_lp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pre_shipment_list_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('logistic_provider_pre_shipment_list_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('client_pre_shipment_list', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pre_shipment_list_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('logistics_provider_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_declaration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('shipped_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shipped_date_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivered_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_state_localized', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tracking_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_webhook_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_webhook_id'], ['webhook_contents.id'], name='shipment_order_volumes_parent_webhook_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shipment_order_volumes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_shipment_order_volumes_id'), 'shipment_order_volumes', ['id'], unique=False)
    op.create_table('inventario_bipagem',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nrserie', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id_caixa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_lote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('patrimonio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('group_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observacao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mensagem_ferramenta_inv', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comentarios', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_user_id'], ['auth_group.id'], name=op.f('inventario_bipagem_group_user_id_1ca7e1a0_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['id_caixa_id'], ['inventario_caixa.id'], name=op.f('inventario_bipagem_id_caixa_id_9d44428c_fk_inventario_caixa_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['id_lote_id'], ['inventario_lotebipagem.id'], name=op.f('inventario_bipagem_id_lote_id_17b34237_fk_inventari'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventario_bipagem_pkey'))
    )
    op.create_index(op.f('inventario_bipagem_id_lote_id_17b34237'), 'inventario_bipagem', ['id_lote_id'], unique=False)
    op.create_index(op.f('inventario_bipagem_id_caixa_id_9d44428c'), 'inventario_bipagem', ['id_caixa_id'], unique=False)
    op.create_index(op.f('inventario_bipagem_group_user_id_1ca7e1a0'), 'inventario_bipagem', ['group_user_id'], unique=False)
    op.create_table('inventario_lotebipagem',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('group_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_created_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_user_txt', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('numero_lote', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_user_id'], ['auth_group.id'], name='inventario_lotebipagem_group_user_id_f82b0ceb_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_created_id'], ['auth_user.id'], name='inventario_lotebipagem_user_created_id_46891968_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='inventario_lotebipagem_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('inventario_lotebipagem_user_created_id_46891968'), 'inventario_lotebipagem', ['user_created_id'], unique=False)
    op.create_index(op.f('inventario_lotebipagem_group_user_id_f82b0ceb'), 'inventario_lotebipagem', ['group_user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_volume_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_volume_id'], ['shipment_order_volumes.id'], name=op.f('products_parent_volume_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('arancia_itemromaneio',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('serial', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('chamado', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filial', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('destino', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('romaneio_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['romaneio_id'], ['arancia_romaneio.id'], name=op.f('arancia_itemromaneio_romaneio_id_2ced4878_fk_arancia_r'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('arancia_itemromaneio_pkey'))
    )
    op.create_index(op.f('arancia_itemromaneio_romaneio_id_2ced4878'), 'arancia_itemromaneio', ['romaneio_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('requests_pkey'))
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_table('shipment_order_volume_state_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shipment_order_volume_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tracking_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('esprinter_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipper_provider_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('shipment_volume_micro_state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('request_origin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_state_localized', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_state_history', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('event_date_iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_volume_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('shipment_order_volume_state_histories_location_id_fkey')),
    sa.ForeignKeyConstraint(['parent_volume_id'], ['shipment_order_volumes.id'], name=op.f('shipment_order_volume_state_histories_parent_volume_id_fkey')),
    sa.ForeignKeyConstraint(['shipment_volume_micro_state_id'], ['shipment_volume_micro_states.id'], name=op.f('shipment_order_volume_state_h_shipment_volume_micro_state__fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shipment_order_volume_state_histories_pkey'))
    )
    op.create_index(op.f('ix_shipment_order_volume_state_histories_id'), 'shipment_order_volume_state_histories', ['id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('django_session_pkey'))
    )
    op.create_index(op.f('django_session_session_key_c0390e0f_like'), 'django_session', ['session_key'], unique=False)
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('licence_plate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey'))
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('inventario_serial',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['inventario_lotebipagem.id'], name=op.f('inventario_serial_lote_id_b8c79bd6_fk_inventario_lotebipagem_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventario_serial_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('inventario_serial_codigo_key'))
    )
    op.create_index(op.f('inventario_serial_lote_id_b8c79bd6'), 'inventario_serial', ['lote_id'], unique=False)
    op.create_index(op.f('inventario_serial_codigo_b75bc703_like'), 'inventario_serial', ['codigo'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_user_user_permissions_pkey')),
    sa.UniqueConstraint('user_id', 'permission_id', name=op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'))
    )
    op.create_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('auth_group_name_a6ea08ec_like'), 'auth_group', ['name'], unique=False)
    op.create_table('aditional_information',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('maquineta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prioridade_simcard', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('aditional_information_pkey'))
    )
    op.create_index(op.f('ix_aditional_information_id'), 'aditional_information', ['id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('arancia_romaneio',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('codigo_rastreio', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('arancia_romaneio_pkey')),
    sa.UniqueConstraint('numero', name=op.f('arancia_romaneio_numero_key'))
    )
    op.create_index(op.f('arancia_romaneio_numero_05bb2a6c_like'), 'arancia_romaneio', ['numero'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_permissions_pkey')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'))
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('shipment_volume_micro_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('i18n_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_order_volume_state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shipment_volume_state_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shipment_volume_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_volume_state_localized', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shipment_volume_micro_states_pkey'))
    )
    op.create_index(op.f('ix_shipment_volume_micro_states_id'), 'shipment_volume_micro_states', ['id'], unique=False)
    op.create_table('logistica_itemromaneio',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('serial', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('chamado', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filial', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('destino', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('romaneio_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['romaneio_id'], ['logistica_romaneio.id'], name=op.f('logistica_itemromane_romaneio_id_d674ec70_fk_logistica'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('logistica_itemromaneio_pkey'))
    )
    op.create_index(op.f('logistica_itemromaneio_romaneio_id_d674ec70'), 'logistica_itemromaneio', ['romaneio_id'], unique=False)
    op.create_table('inventario_dados_importados',
    sa.Column('modalidade_comercial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('serial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_sistema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_usuario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('opl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('serial_fabricante', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('equipamento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('centro', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deposito', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('modificado_por', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modificado_em', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ct', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_aquisicao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nome_ct', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nome_fornecedor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mensagem_ferramenta_inv', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vl_aquisicao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('vl_residual', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('federal_tax_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('license', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cell_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('drivers_pkey'))
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_user_groups_group_id_97559544_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('auth_user_groups_user_id_6a12ed8b_fk_auth_user_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_user_groups_pkey')),
    sa.UniqueConstraint('user_id', 'group_id', name=op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'))
    )
    op.create_index(op.f('auth_user_groups_user_id_6a12ed8b'), 'auth_user_groups', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_groups_group_id_97559544'), 'auth_user_groups', ['group_id'], unique=False)
    # ### end Alembic commands ###
