"""carros

Revision ID: b76828ecd2ad
Revises: b3515b8f8086
Create Date: 2025-07-10 11:22:01.584578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76828ecd2ad'
down_revision: Union[str, Sequence[str], None] = 'b3515b8f8086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carrinhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cor', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('versao', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Carrinhos_id'), 'Carrinhos', ['id'], unique=False)
    op.create_index(op.f('ix_Carrinhos_modelo'), 'Carrinhos', ['modelo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_CarTeste',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('TB_CarTeste_pkey'))
    )
    op.create_index(op.f('ix_TB_CarTeste_year'), 'TB_CarTeste', ['year'], unique=False)
    op.create_index(op.f('ix_TB_CarTeste_model'), 'TB_CarTeste', ['model'], unique=False)
    op.create_index(op.f('ix_TB_CarTeste_id'), 'TB_CarTeste', ['id'], unique=False)
    op.drop_index(op.f('ix_Carrinhos_modelo'), table_name='Carrinhos')
    op.drop_index(op.f('ix_Carrinhos_id'), table_name='Carrinhos')
    op.drop_table('Carrinhos')
    # ### end Alembic commands ###
